nodeLinker: node-modules
enableGlobalCache: false

npmRegistryServer: "https://registry.npmjs.org"

# Permitir modificaciones al archivo de bloqueo durante la instalación
immutablePatterns: []
enableImmutableInstalls: false

# Ignorar advertencias de dependencias peer
logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0061
    level: discard
